//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EnvoHstCrdComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnvoHstCrdComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cli" type="{}CliComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CnpjIf" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="99999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CnpjGbd" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="99999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NrRms" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SeqlRms" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CmdoRms" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="I"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NrRmsRlc">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="FmtRms" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="C"/>
 *             &lt;enumeration value="I"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DtRms" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DtRefBaseItno" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnvoHstCrdComplexType", propOrder = {
    "cli"
})
public class EnvoHstCrdComplexType {

    @XmlElement(name = "Cli")
    protected List<CliComplexType> cli;
    @XmlAttribute(name = "CnpjIf", required = true)
    protected long cnpjIf;
    @XmlAttribute(name = "CnpjGbd", required = true)
    protected long cnpjGbd;
    @XmlAttribute(name = "NrRms", required = true)
    protected int nrRms;
    @XmlAttribute(name = "SeqlRms", required = true)
    protected int seqlRms;
    @XmlAttribute(name = "CmdoRms", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cmdoRms;
    @XmlAttribute(name = "NrRmsRlc")
    protected Integer nrRmsRlc;
    @XmlAttribute(name = "FmtRms", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fmtRms;
    @XmlAttribute(name = "DtRms", required = true)
    protected String dtRms;
    @XmlAttribute(name = "DtRefBaseItno", required = true)
    protected String dtRefBaseItno;

    /**
     * Gets the value of the cli property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cli property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCli().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CliComplexType }
     * 
     * 
     */
    public List<CliComplexType> getCli() {
        if (cli == null) {
            cli = new ArrayList<CliComplexType>();
        }
        return this.cli;
    }

    /**
     * Gets the value of the cnpjIf property.
     * 
     */
    public long getCnpjIf() {
        return cnpjIf;
    }

    /**
     * Sets the value of the cnpjIf property.
     * 
     */
    public void setCnpjIf(long value) {
        this.cnpjIf = value;
    }

    /**
     * Gets the value of the cnpjGbd property.
     * 
     */
    public long getCnpjGbd() {
        return cnpjGbd;
    }

    /**
     * Sets the value of the cnpjGbd property.
     * 
     */
    public void setCnpjGbd(long value) {
        this.cnpjGbd = value;
    }

    /**
     * Gets the value of the nrRms property.
     * 
     */
    public int getNrRms() {
        return nrRms;
    }

    /**
     * Sets the value of the nrRms property.
     * 
     */
    public void setNrRms(int value) {
        this.nrRms = value;
    }

    /**
     * Gets the value of the seqlRms property.
     * 
     */
    public int getSeqlRms() {
        return seqlRms;
    }

    /**
     * Sets the value of the seqlRms property.
     * 
     */
    public void setSeqlRms(int value) {
        this.seqlRms = value;
    }

    /**
     * Gets the value of the cmdoRms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdoRms() {
        return cmdoRms;
    }

    /**
     * Sets the value of the cmdoRms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdoRms(String value) {
        this.cmdoRms = value;
    }

    /**
     * Gets the value of the nrRmsRlc property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNrRmsRlc() {
        return nrRmsRlc;
    }

    /**
     * Sets the value of the nrRmsRlc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNrRmsRlc(Integer value) {
        this.nrRmsRlc = value;
    }

    /**
     * Gets the value of the fmtRms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFmtRms() {
        return fmtRms;
    }

    /**
     * Sets the value of the fmtRms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFmtRms(String value) {
        this.fmtRms = value;
    }

    /**
     * Gets the value of the dtRms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtRms() {
        return dtRms;
    }

    /**
     * Sets the value of the dtRms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtRms(String value) {
        this.dtRms = value;
    }

    /**
     * Gets the value of the dtRefBaseItno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtRefBaseItno() {
        return dtRefBaseItno;
    }

    /**
     * Sets the value of the dtRefBaseItno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtRefBaseItno(String value) {
        this.dtRefBaseItno = value;
    }

}
