//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for FatFchdFutComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FatFchdFutComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DtVnctFatFchdFut">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VlTtlPgrFatFchdFut">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="-999999999999999"/>
 *             &lt;maxInclusive value="999999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VlMinPgrFatFchdFut">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="999999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CmdoFatFchdFut">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="I"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FatFchdFutComplexType")
public class FatFchdFutComplexType {

    @XmlAttribute(name = "DtVnctFatFchdFut")
    protected String dtVnctFatFchdFut;
    @XmlAttribute(name = "VlTtlPgrFatFchdFut")
    protected Long vlTtlPgrFatFchdFut;
    @XmlAttribute(name = "VlMinPgrFatFchdFut")
    protected Long vlMinPgrFatFchdFut;
    @XmlAttribute(name = "CmdoFatFchdFut")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cmdoFatFchdFut;

    /**
     * Gets the value of the dtVnctFatFchdFut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtVnctFatFchdFut() {
        return dtVnctFatFchdFut;
    }

    /**
     * Sets the value of the dtVnctFatFchdFut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtVnctFatFchdFut(String value) {
        this.dtVnctFatFchdFut = value;
    }

    /**
     * Gets the value of the vlTtlPgrFatFchdFut property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlTtlPgrFatFchdFut() {
        return vlTtlPgrFatFchdFut;
    }

    /**
     * Sets the value of the vlTtlPgrFatFchdFut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlTtlPgrFatFchdFut(Long value) {
        this.vlTtlPgrFatFchdFut = value;
    }

    /**
     * Gets the value of the vlMinPgrFatFchdFut property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlMinPgrFatFchdFut() {
        return vlMinPgrFatFchdFut;
    }

    /**
     * Sets the value of the vlMinPgrFatFchdFut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlMinPgrFatFchdFut(Long value) {
        this.vlMinPgrFatFchdFut = value;
    }

    /**
     * Gets the value of the cmdoFatFchdFut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdoFatFchdFut() {
        return cmdoFatFchdFut;
    }

    /**
     * Sets the value of the cmdoFatFchdFut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdoFatFchdFut(String value) {
        this.cmdoFatFchdFut = value;
    }

}
