//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for FchtAntComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FchtAntComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DtFchtAnt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SdoUtlzFchtAnt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="999999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CmdoFchtAnt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="I"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FchtAntComplexType")
public class FchtAntComplexType {

    @XmlAttribute(name = "DtFchtAnt")
    protected String dtFchtAnt;
    @XmlAttribute(name = "SdoUtlzFchtAnt")
    protected Long sdoUtlzFchtAnt;
    @XmlAttribute(name = "CmdoFchtAnt")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cmdoFchtAnt;

    /**
     * Gets the value of the dtFchtAnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtFchtAnt() {
        return dtFchtAnt;
    }

    /**
     * Sets the value of the dtFchtAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtFchtAnt(String value) {
        this.dtFchtAnt = value;
    }

    /**
     * Gets the value of the sdoUtlzFchtAnt property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSdoUtlzFchtAnt() {
        return sdoUtlzFchtAnt;
    }

    /**
     * Sets the value of the sdoUtlzFchtAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSdoUtlzFchtAnt(Long value) {
        this.sdoUtlzFchtAnt = value;
    }

    /**
     * Gets the value of the cmdoFchtAnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdoFchtAnt() {
        return cmdoFchtAnt;
    }

    /**
     * Sets the value of the cmdoFchtAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdoFchtAnt(String value) {
        this.cmdoFchtAnt = value;
    }

}
