//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for FchtAtuComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FchtAtuComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DtFchtAtu">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SdoUtlzFchtAtu">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="999999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CmdoFchtAtu">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="I"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FchtAtuComplexType")
public class FchtAtuComplexType {

    @XmlAttribute(name = "DtFchtAtu")
    protected String dtFchtAtu;
    @XmlAttribute(name = "SdoUtlzFchtAtu")
    protected Long sdoUtlzFchtAtu;
    @XmlAttribute(name = "CmdoFchtAtu")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cmdoFchtAtu;

    /**
     * Gets the value of the dtFchtAtu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtFchtAtu() {
        return dtFchtAtu;
    }

    /**
     * Sets the value of the dtFchtAtu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtFchtAtu(String value) {
        this.dtFchtAtu = value;
    }

    /**
     * Gets the value of the sdoUtlzFchtAtu property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSdoUtlzFchtAtu() {
        return sdoUtlzFchtAtu;
    }

    /**
     * Sets the value of the sdoUtlzFchtAtu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSdoUtlzFchtAtu(Long value) {
        this.sdoUtlzFchtAtu = value;
    }

    /**
     * Gets the value of the cmdoFchtAtu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdoFchtAtu() {
        return cmdoFchtAtu;
    }

    /**
     * Sets the value of the cmdoFchtAtu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdoFchtAtu(String value) {
        this.cmdoFchtAtu = value;
    }

}
