//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for OprComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OprComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="DetOpr" type="{}DetOprComplexType"/>
 *         &lt;element name="PclAnt" type="{}PclAntComplexType"/>
 *         &lt;element name="PgtoAvls" type="{}PgtoAvlsComplexType"/>
 *         &lt;element name="PclFut" type="{}PclFutComplexType"/>
 *         &lt;element name="FatFchdAnt" type="{}FatFchdAntComplexType"/>
 *         &lt;element name="FatFchdFut" type="{}FatFchdFutComplexType"/>
 *         &lt;element name="FchtAnt" type="{}FchtAntComplexType"/>
 *         &lt;element name="FchtAtu" type="{}FchtAtuComplexType"/>
 *         &lt;element name="PclAntCsr" type="{}PclAntCsrComplexType"/>
 *         &lt;element name="PclFutCsr" type="{}PclFutCsrComplexType"/>
 *         &lt;element name="PgtoAvlsCsr" type="{}PgtoAvlsCsrComplexType"/>
 *       &lt;/choice>
 *       &lt;attribute name="NrUnco">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="40"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PrfAg">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="9999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NrCtr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="20"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DtCtrc">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CdMdld">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="A01"/>
 *             &lt;enumeration value="A02"/>
 *             &lt;enumeration value="A04"/>
 *             &lt;enumeration value="A05"/>
 *             &lt;enumeration value="A99"/>
 *             &lt;enumeration value="B01"/>
 *             &lt;enumeration value="B02"/>
 *             &lt;enumeration value="B03"/>
 *             &lt;enumeration value="B04"/>
 *             &lt;enumeration value="B05"/>
 *             &lt;enumeration value="B06"/>
 *             &lt;enumeration value="B07"/>
 *             &lt;enumeration value="B99"/>
 *             &lt;enumeration value="C01"/>
 *             &lt;enumeration value="D01"/>
 *             &lt;enumeration value="E01"/>
 *             &lt;enumeration value="E02"/>
 *             &lt;enumeration value="F01"/>
 *             &lt;enumeration value="G01"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DtAprc">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CnpjCtrc">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="99999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TipRst">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="C"/>
 *             &lt;enumeration value="F"/>
 *             &lt;enumeration value="I"/>
 *             &lt;enumeration value="L"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CmdoOpr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="I"/>
 *             &lt;enumeration value="S"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="IdfcCliCtrt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="99999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OprComplexType", propOrder = {
    "detOprOrPclAntOrPgtoAvls"
})
public class OprComplexType {

    @XmlElements({
        @XmlElement(name = "DetOpr", type = DetOprComplexType.class),
        @XmlElement(name = "PclAnt", type = PclAntComplexType.class),
        @XmlElement(name = "PgtoAvls", type = PgtoAvlsComplexType.class),
        @XmlElement(name = "PclFut", type = PclFutComplexType.class),
        @XmlElement(name = "FatFchdAnt", type = FatFchdAntComplexType.class),
        @XmlElement(name = "FatFchdFut", type = FatFchdFutComplexType.class),
        @XmlElement(name = "FchtAnt", type = FchtAntComplexType.class),
        @XmlElement(name = "FchtAtu", type = FchtAtuComplexType.class),
        @XmlElement(name = "PclAntCsr", type = PclAntCsrComplexType.class),
        @XmlElement(name = "PclFutCsr", type = PclFutCsrComplexType.class),
        @XmlElement(name = "PgtoAvlsCsr", type = PgtoAvlsCsrComplexType.class)
    })
    protected List<Object> detOprOrPclAntOrPgtoAvls;
    @XmlAttribute(name = "NrUnco")
    protected String nrUnco;
    @XmlAttribute(name = "PrfAg")
    protected Short prfAg;
    @XmlAttribute(name = "NrCtr")
    protected String nrCtr;
    @XmlAttribute(name = "DtCtrc")
    protected String dtCtrc;
    @XmlAttribute(name = "CdMdld")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cdMdld;
    @XmlAttribute(name = "DtAprc")
    protected String dtAprc;
    @XmlAttribute(name = "CnpjCtrc")
    protected Long cnpjCtrc;
    @XmlAttribute(name = "TipRst")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tipRst;
    @XmlAttribute(name = "CmdoOpr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cmdoOpr;
    @XmlAttribute(name = "IdfcCliCtrt")
    protected Long idfcCliCtrt;

    /**
     * Gets the value of the detOprOrPclAntOrPgtoAvls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detOprOrPclAntOrPgtoAvls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetOprOrPclAntOrPgtoAvls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetOprComplexType }
     * {@link PclAntComplexType }
     * {@link PgtoAvlsComplexType }
     * {@link PclFutComplexType }
     * {@link FatFchdAntComplexType }
     * {@link FatFchdFutComplexType }
     * {@link FchtAntComplexType }
     * {@link FchtAtuComplexType }
     * {@link PclAntCsrComplexType }
     * {@link PclFutCsrComplexType }
     * {@link PgtoAvlsCsrComplexType }
     * 
     * 
     */
    public List<Object> getDetOprOrPclAntOrPgtoAvls() {
        if (detOprOrPclAntOrPgtoAvls == null) {
            detOprOrPclAntOrPgtoAvls = new ArrayList<Object>();
        }
        return this.detOprOrPclAntOrPgtoAvls;
    }

    /**
     * Gets the value of the nrUnco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrUnco() {
        return nrUnco;
    }

    /**
     * Sets the value of the nrUnco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrUnco(String value) {
        this.nrUnco = value;
    }

    /**
     * Gets the value of the prfAg property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPrfAg() {
        return prfAg;
    }

    /**
     * Sets the value of the prfAg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPrfAg(Short value) {
        this.prfAg = value;
    }

    /**
     * Gets the value of the nrCtr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrCtr() {
        return nrCtr;
    }

    /**
     * Sets the value of the nrCtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrCtr(String value) {
        this.nrCtr = value;
    }

    /**
     * Gets the value of the dtCtrc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtCtrc() {
        return dtCtrc;
    }

    /**
     * Sets the value of the dtCtrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtCtrc(String value) {
        this.dtCtrc = value;
    }

    /**
     * Gets the value of the cdMdld property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdMdld() {
        return cdMdld;
    }

    /**
     * Sets the value of the cdMdld property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdMdld(String value) {
        this.cdMdld = value;
    }

    /**
     * Gets the value of the dtAprc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtAprc() {
        return dtAprc;
    }

    /**
     * Sets the value of the dtAprc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtAprc(String value) {
        this.dtAprc = value;
    }

    /**
     * Gets the value of the cnpjCtrc property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCnpjCtrc() {
        return cnpjCtrc;
    }

    /**
     * Sets the value of the cnpjCtrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCnpjCtrc(Long value) {
        this.cnpjCtrc = value;
    }

    /**
     * Gets the value of the tipRst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipRst() {
        return tipRst;
    }

    /**
     * Sets the value of the tipRst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipRst(String value) {
        this.tipRst = value;
    }

    /**
     * Gets the value of the cmdoOpr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdoOpr() {
        return cmdoOpr;
    }

    /**
     * Sets the value of the cmdoOpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdoOpr(String value) {
        this.cmdoOpr = value;
    }

    /**
     * Gets the value of the idfcCliCtrt property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdfcCliCtrt() {
        return idfcCliCtrt;
    }

    /**
     * Sets the value of the idfcCliCtrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdfcCliCtrt(Long value) {
        this.idfcCliCtrt = value;
    }

}
