//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PclAntCsrComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PclAntCsrComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="PgtoPclAntCsr" type="{}PgtoPclAntCsrComplexType"/>
 *       &lt;/choice>
 *       &lt;attribute name="DtVnctPclAntCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PercPclAntCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="B"/>
 *             &lt;enumeration value="D"/>
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="M"/>
 *             &lt;enumeration value="Q"/>
 *             &lt;enumeration value="S"/>
 *             &lt;enumeration value="T"/>
 *             &lt;enumeration value="W"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VlPclAntCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="999999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CmdoPclAntCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="I"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PclAntCsrComplexType", propOrder = {
    "pgtoPclAntCsr"
})
public class PclAntCsrComplexType {

    @XmlElement(name = "PgtoPclAntCsr")
    protected List<PgtoPclAntCsrComplexType> pgtoPclAntCsr;
    @XmlAttribute(name = "DtVnctPclAntCsr")
    protected String dtVnctPclAntCsr;
    @XmlAttribute(name = "PercPclAntCsr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String percPclAntCsr;
    @XmlAttribute(name = "VlPclAntCsr")
    protected Long vlPclAntCsr;
    @XmlAttribute(name = "CmdoPclAntCsr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cmdoPclAntCsr;

    /**
     * Gets the value of the pgtoPclAntCsr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pgtoPclAntCsr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPgtoPclAntCsr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PgtoPclAntCsrComplexType }
     * 
     * 
     */
    public List<PgtoPclAntCsrComplexType> getPgtoPclAntCsr() {
        if (pgtoPclAntCsr == null) {
            pgtoPclAntCsr = new ArrayList<PgtoPclAntCsrComplexType>();
        }
        return this.pgtoPclAntCsr;
    }

    /**
     * Gets the value of the dtVnctPclAntCsr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtVnctPclAntCsr() {
        return dtVnctPclAntCsr;
    }

    /**
     * Sets the value of the dtVnctPclAntCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtVnctPclAntCsr(String value) {
        this.dtVnctPclAntCsr = value;
    }

    /**
     * Gets the value of the percPclAntCsr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercPclAntCsr() {
        return percPclAntCsr;
    }

    /**
     * Sets the value of the percPclAntCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercPclAntCsr(String value) {
        this.percPclAntCsr = value;
    }

    /**
     * Gets the value of the vlPclAntCsr property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlPclAntCsr() {
        return vlPclAntCsr;
    }

    /**
     * Sets the value of the vlPclAntCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlPclAntCsr(Long value) {
        this.vlPclAntCsr = value;
    }

    /**
     * Gets the value of the cmdoPclAntCsr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdoPclAntCsr() {
        return cmdoPclAntCsr;
    }

    /**
     * Sets the value of the cmdoPclAntCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdoPclAntCsr(String value) {
        this.cmdoPclAntCsr = value;
    }

}
