//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PclAntComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PclAntComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="PgtoPclAnt" type="{}PgtoPclAntComplexType"/>
 *       &lt;/choice>
 *       &lt;attribute name="DtVnctPclAnt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PercPclAnt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="B"/>
 *             &lt;enumeration value="D"/>
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="M"/>
 *             &lt;enumeration value="Q"/>
 *             &lt;enumeration value="S"/>
 *             &lt;enumeration value="T"/>
 *             &lt;enumeration value="W"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VlPclAnt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="999999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CmdoPclAnt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="I"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PclAntComplexType", propOrder = {
    "pgtoPclAnt"
})
public class PclAntComplexType {

    @XmlElement(name = "PgtoPclAnt")
    protected List<PgtoPclAntComplexType> pgtoPclAnt;
    @XmlAttribute(name = "DtVnctPclAnt")
    protected String dtVnctPclAnt;
    @XmlAttribute(name = "PercPclAnt")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String percPclAnt;
    @XmlAttribute(name = "VlPclAnt")
    protected Long vlPclAnt;
    @XmlAttribute(name = "CmdoPclAnt")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cmdoPclAnt;

    /**
     * Gets the value of the pgtoPclAnt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pgtoPclAnt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPgtoPclAnt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PgtoPclAntComplexType }
     * 
     * 
     */
    public List<PgtoPclAntComplexType> getPgtoPclAnt() {
        if (pgtoPclAnt == null) {
            pgtoPclAnt = new ArrayList<PgtoPclAntComplexType>();
        }
        return this.pgtoPclAnt;
    }

    /**
     * Gets the value of the dtVnctPclAnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtVnctPclAnt() {
        return dtVnctPclAnt;
    }

    /**
     * Sets the value of the dtVnctPclAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtVnctPclAnt(String value) {
        this.dtVnctPclAnt = value;
    }

    /**
     * Gets the value of the percPclAnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercPclAnt() {
        return percPclAnt;
    }

    /**
     * Sets the value of the percPclAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercPclAnt(String value) {
        this.percPclAnt = value;
    }

    /**
     * Gets the value of the vlPclAnt property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlPclAnt() {
        return vlPclAnt;
    }

    /**
     * Sets the value of the vlPclAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlPclAnt(Long value) {
        this.vlPclAnt = value;
    }

    /**
     * Gets the value of the cmdoPclAnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdoPclAnt() {
        return cmdoPclAnt;
    }

    /**
     * Sets the value of the cmdoPclAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdoPclAnt(String value) {
        this.cmdoPclAnt = value;
    }

}
