//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PclFutCsrComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PclFutCsrComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DtVnctPrxPclCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PercPclFutCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="B"/>
 *             &lt;enumeration value="D"/>
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="M"/>
 *             &lt;enumeration value="Q"/>
 *             &lt;enumeration value="S"/>
 *             &lt;enumeration value="T"/>
 *             &lt;enumeration value="W"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VlPrxPclCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="QtPclVncrCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="QtPclPgrCtCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PclFutCsrComplexType")
public class PclFutCsrComplexType {

    @XmlAttribute(name = "DtVnctPrxPclCsr")
    protected String dtVnctPrxPclCsr;
    @XmlAttribute(name = "PercPclFutCsr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String percPclFutCsr;
    @XmlAttribute(name = "VlPrxPclCsr")
    protected Long vlPrxPclCsr;
    @XmlAttribute(name = "QtPclVncrCsr")
    protected Short qtPclVncrCsr;
    @XmlAttribute(name = "QtPclPgrCtCsr")
    protected Short qtPclPgrCtCsr;

    /**
     * Gets the value of the dtVnctPrxPclCsr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtVnctPrxPclCsr() {
        return dtVnctPrxPclCsr;
    }

    /**
     * Sets the value of the dtVnctPrxPclCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtVnctPrxPclCsr(String value) {
        this.dtVnctPrxPclCsr = value;
    }

    /**
     * Gets the value of the percPclFutCsr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercPclFutCsr() {
        return percPclFutCsr;
    }

    /**
     * Sets the value of the percPclFutCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercPclFutCsr(String value) {
        this.percPclFutCsr = value;
    }

    /**
     * Gets the value of the vlPrxPclCsr property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlPrxPclCsr() {
        return vlPrxPclCsr;
    }

    /**
     * Sets the value of the vlPrxPclCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlPrxPclCsr(Long value) {
        this.vlPrxPclCsr = value;
    }

    /**
     * Gets the value of the qtPclVncrCsr property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getQtPclVncrCsr() {
        return qtPclVncrCsr;
    }

    /**
     * Sets the value of the qtPclVncrCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setQtPclVncrCsr(Short value) {
        this.qtPclVncrCsr = value;
    }

    /**
     * Gets the value of the qtPclPgrCtCsr property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getQtPclPgrCtCsr() {
        return qtPclPgrCtCsr;
    }

    /**
     * Sets the value of the qtPclPgrCtCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setQtPclPgrCtCsr(Short value) {
        this.qtPclPgrCtCsr = value;
    }

}
