//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PclFutComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PclFutComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DtVnctPrxPcl">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PercPclFut">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="B"/>
 *             &lt;enumeration value="D"/>
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="M"/>
 *             &lt;enumeration value="Q"/>
 *             &lt;enumeration value="S"/>
 *             &lt;enumeration value="T"/>
 *             &lt;enumeration value="W"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VlPrxPcl">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="QtPclVncr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="QtPclPgr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PclFutComplexType")
public class PclFutComplexType {

    @XmlAttribute(name = "DtVnctPrxPcl")
    protected String dtVnctPrxPcl;
    @XmlAttribute(name = "PercPclFut")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String percPclFut;
    @XmlAttribute(name = "VlPrxPcl")
    protected Long vlPrxPcl;
    @XmlAttribute(name = "QtPclVncr")
    protected Short qtPclVncr;
    @XmlAttribute(name = "QtPclPgr")
    protected Short qtPclPgr;

    /**
     * Gets the value of the dtVnctPrxPcl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtVnctPrxPcl() {
        return dtVnctPrxPcl;
    }

    /**
     * Sets the value of the dtVnctPrxPcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtVnctPrxPcl(String value) {
        this.dtVnctPrxPcl = value;
    }

    /**
     * Gets the value of the percPclFut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercPclFut() {
        return percPclFut;
    }

    /**
     * Sets the value of the percPclFut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercPclFut(String value) {
        this.percPclFut = value;
    }

    /**
     * Gets the value of the vlPrxPcl property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlPrxPcl() {
        return vlPrxPcl;
    }

    /**
     * Sets the value of the vlPrxPcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlPrxPcl(Long value) {
        this.vlPrxPcl = value;
    }

    /**
     * Gets the value of the qtPclVncr property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getQtPclVncr() {
        return qtPclVncr;
    }

    /**
     * Sets the value of the qtPclVncr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setQtPclVncr(Short value) {
        this.qtPclVncr = value;
    }

    /**
     * Gets the value of the qtPclPgr property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getQtPclPgr() {
        return qtPclPgr;
    }

    /**
     * Sets the value of the qtPclPgr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setQtPclPgr(Short value) {
        this.qtPclPgr = value;
    }

}
