//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PgtoFatFchdComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PgtoFatFchdComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DtPgtoFatFchdAnt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VlPgtoFatFchdAnt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="999999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PgtoFatFchdComplexType")
public class PgtoFatFchdComplexType {

    @XmlAttribute(name = "DtPgtoFatFchdAnt")
    protected String dtPgtoFatFchdAnt;
    @XmlAttribute(name = "VlPgtoFatFchdAnt")
    protected Long vlPgtoFatFchdAnt;

    /**
     * Gets the value of the dtPgtoFatFchdAnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtPgtoFatFchdAnt() {
        return dtPgtoFatFchdAnt;
    }

    /**
     * Sets the value of the dtPgtoFatFchdAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtPgtoFatFchdAnt(String value) {
        this.dtPgtoFatFchdAnt = value;
    }

    /**
     * Gets the value of the vlPgtoFatFchdAnt property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlPgtoFatFchdAnt() {
        return vlPgtoFatFchdAnt;
    }

    /**
     * Sets the value of the vlPgtoFatFchdAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlPgtoFatFchdAnt(Long value) {
        this.vlPgtoFatFchdAnt = value;
    }

}
