//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PgtoPclAntComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PgtoPclAntComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DtPgtoPclAnt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VlPgtoPclAnt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="999999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PgtoPclAntComplexType")
public class PgtoPclAntComplexType {

    @XmlAttribute(name = "DtPgtoPclAnt")
    protected String dtPgtoPclAnt;
    @XmlAttribute(name = "VlPgtoPclAnt")
    protected Long vlPgtoPclAnt;

    /**
     * Gets the value of the dtPgtoPclAnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtPgtoPclAnt() {
        return dtPgtoPclAnt;
    }

    /**
     * Sets the value of the dtPgtoPclAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtPgtoPclAnt(String value) {
        this.dtPgtoPclAnt = value;
    }

    /**
     * Gets the value of the vlPgtoPclAnt property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlPgtoPclAnt() {
        return vlPgtoPclAnt;
    }

    /**
     * Sets the value of the vlPgtoPclAnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlPgtoPclAnt(Long value) {
        this.vlPgtoPclAnt = value;
    }

}
