//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PgtoAvlsComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PgtoAvlsComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DtPgtoAvls">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VlPgtoAvls">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TipPgtoAvls">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="L"/>
 *             &lt;enumeration value="P"/>
 *             &lt;enumeration value="S"/>
 *             &lt;enumeration value="T"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CmdoPgtoAvls">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="I"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PgtoAvlsComplexType")
public class PgtoAvlsComplexType {

    @XmlAttribute(name = "DtPgtoAvls")
    protected String dtPgtoAvls;
    @XmlAttribute(name = "VlPgtoAvls")
    protected Long vlPgtoAvls;
    @XmlAttribute(name = "TipPgtoAvls")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tipPgtoAvls;
    @XmlAttribute(name = "CmdoPgtoAvls")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cmdoPgtoAvls;

    /**
     * Gets the value of the dtPgtoAvls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtPgtoAvls() {
        return dtPgtoAvls;
    }

    /**
     * Sets the value of the dtPgtoAvls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtPgtoAvls(String value) {
        this.dtPgtoAvls = value;
    }

    /**
     * Gets the value of the vlPgtoAvls property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlPgtoAvls() {
        return vlPgtoAvls;
    }

    /**
     * Sets the value of the vlPgtoAvls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlPgtoAvls(Long value) {
        this.vlPgtoAvls = value;
    }

    /**
     * Gets the value of the tipPgtoAvls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipPgtoAvls() {
        return tipPgtoAvls;
    }

    /**
     * Sets the value of the tipPgtoAvls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipPgtoAvls(String value) {
        this.tipPgtoAvls = value;
    }

    /**
     * Gets the value of the cmdoPgtoAvls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdoPgtoAvls() {
        return cmdoPgtoAvls;
    }

    /**
     * Sets the value of the cmdoPgtoAvls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdoPgtoAvls(String value) {
        this.cmdoPgtoAvls = value;
    }

}
