//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:40:19 AM BRT 
//


package br.com.poc.model.acpo025.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PgtoAvlsCsrComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PgtoAvlsCsrComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DtPgtoAvlsCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VlPgtoAvlsCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TipPgtoAvlsCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="L"/>
 *             &lt;enumeration value="P"/>
 *             &lt;enumeration value="S"/>
 *             &lt;enumeration value="T"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CmdoPgtoAvlsCsr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="I"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PgtoAvlsCsrComplexType")
public class PgtoAvlsCsrComplexType {

    @XmlAttribute(name = "DtPgtoAvlsCsr")
    protected String dtPgtoAvlsCsr;
    @XmlAttribute(name = "VlPgtoAvlsCsr")
    protected Long vlPgtoAvlsCsr;
    @XmlAttribute(name = "TipPgtoAvlsCsr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tipPgtoAvlsCsr;
    @XmlAttribute(name = "CmdoPgtoAvlsCsr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cmdoPgtoAvlsCsr;

    /**
     * Gets the value of the dtPgtoAvlsCsr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtPgtoAvlsCsr() {
        return dtPgtoAvlsCsr;
    }

    /**
     * Sets the value of the dtPgtoAvlsCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtPgtoAvlsCsr(String value) {
        this.dtPgtoAvlsCsr = value;
    }

    /**
     * Gets the value of the vlPgtoAvlsCsr property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlPgtoAvlsCsr() {
        return vlPgtoAvlsCsr;
    }

    /**
     * Sets the value of the vlPgtoAvlsCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlPgtoAvlsCsr(Long value) {
        this.vlPgtoAvlsCsr = value;
    }

    /**
     * Gets the value of the tipPgtoAvlsCsr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipPgtoAvlsCsr() {
        return tipPgtoAvlsCsr;
    }

    /**
     * Sets the value of the tipPgtoAvlsCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipPgtoAvlsCsr(String value) {
        this.tipPgtoAvlsCsr = value;
    }

    /**
     * Gets the value of the cmdoPgtoAvlsCsr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdoPgtoAvlsCsr() {
        return cmdoPgtoAvlsCsr;
    }

    /**
     * Sets the value of the cmdoPgtoAvlsCsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdoPgtoAvlsCsr(String value) {
        this.cmdoPgtoAvlsCsr = value;
    }

}
