//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:33:42 AM BRT 
//


package br.com.poc.model.acpo021.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CliComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CliComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="EndCli" type="{}EndCliComplexType" maxOccurs="5"/>
 *           &lt;element name="TelCli" type="{}TelCliComplexType" maxOccurs="5"/>
 *           &lt;element name="EndEtnCli" type="{}EndEtnCliComplexType" maxOccurs="5"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="TipCli" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="IdfcCli" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="99999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NmCli" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="60"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CliComplexType", propOrder = {
    "endCli",
    "telCli",
    "endEtnCli"
})
public class CliComplexType {

    @XmlElement(name = "EndCli")
    protected List<EndCliComplexType> endCli;
    @XmlElement(name = "TelCli")
    protected List<TelCliComplexType> telCli;
    @XmlElement(name = "EndEtnCli")
    protected List<EndEtnCliComplexType> endEtnCli;
    @XmlAttribute(name = "TipCli", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tipCli;
    @XmlAttribute(name = "IdfcCli", required = true)
    protected long idfcCli;
    @XmlAttribute(name = "NmCli", required = true)
    protected String nmCli;

    /**
     * Gets the value of the endCli property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the endCli property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEndCli().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EndCliComplexType }
     * 
     * 
     */
    public List<EndCliComplexType> getEndCli() {
        if (endCli == null) {
            endCli = new ArrayList<EndCliComplexType>();
        }
        return this.endCli;
    }

    /**
     * Gets the value of the telCli property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telCli property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelCli().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TelCliComplexType }
     * 
     * 
     */
    public List<TelCliComplexType> getTelCli() {
        if (telCli == null) {
            telCli = new ArrayList<TelCliComplexType>();
        }
        return this.telCli;
    }

    /**
     * Gets the value of the endEtnCli property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the endEtnCli property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEndEtnCli().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EndEtnCliComplexType }
     * 
     * 
     */
    public List<EndEtnCliComplexType> getEndEtnCli() {
        if (endEtnCli == null) {
            endEtnCli = new ArrayList<EndEtnCliComplexType>();
        }
        return this.endEtnCli;
    }

    /**
     * Gets the value of the tipCli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipCli() {
        return tipCli;
    }

    /**
     * Sets the value of the tipCli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipCli(String value) {
        this.tipCli = value;
    }

    /**
     * Gets the value of the idfcCli property.
     * 
     */
    public long getIdfcCli() {
        return idfcCli;
    }

    /**
     * Sets the value of the idfcCli property.
     * 
     */
    public void setIdfcCli(long value) {
        this.idfcCli = value;
    }

    /**
     * Gets the value of the nmCli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmCli() {
        return nmCli;
    }

    /**
     * Sets the value of the nmCli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmCli(String value) {
        this.nmCli = value;
    }

}
