//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:33:42 AM BRT 
//


package br.com.poc.model.acpo021.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EnvoCad_QNAME = new QName("", "EnvoCad");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnvoCadComplexType }
     * 
     */
    public EnvoCadComplexType createEnvoCadComplexType() {
        return new EnvoCadComplexType();
    }

    /**
     * Create an instance of {@link TelCliComplexType }
     * 
     */
    public TelCliComplexType createTelCliComplexType() {
        return new TelCliComplexType();
    }

    /**
     * Create an instance of {@link EndCliComplexType }
     * 
     */
    public EndCliComplexType createEndCliComplexType() {
        return new EndCliComplexType();
    }

    /**
     * Create an instance of {@link CliComplexType }
     * 
     */
    public CliComplexType createCliComplexType() {
        return new CliComplexType();
    }

    /**
     * Create an instance of {@link EndEtnCliComplexType }
     * 
     */
    public EndEtnCliComplexType createEndEtnCliComplexType() {
        return new EndEtnCliComplexType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvoCadComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EnvoCad")
    public JAXBElement<EnvoCadComplexType> createEnvoCad(EnvoCadComplexType value) {
        return new JAXBElement<EnvoCadComplexType>(_EnvoCad_QNAME, EnvoCadComplexType.class, null, value);
    }

}
