server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 1000KB
      max-request-size: 1000KB

sms-dev:
  key: TKA4CTVZHYXYCABB4YJSGVPK97QH6SZMAIH7QI9LMPTG2WNHI957SFF3S1LILULRHF53SLXQOC8ISD1SHVPY7EP2J3QCCVD35YJVHK87MEQKSHW9WAHT9BU1IVF5GATT
  type: 9
  name: smsDev
  url: https://api.smsdev.com.br/v1
  dateSchedule:
  hourSchedule:
  enable: false

komunique:
  id: 0056353f-fd66-11ec-84d0-0a2a974a592c
  token: 0a2e1ea6687c62950265e19478cde695
  name: komunique
  url: https://api.komunique.com.br/v1
  enable: true
