apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: frontend-deployment
        image: 848175180062.dkr.ecr.us-east-1.amazonaws.com/workshop-ecr-repository/frontend:v1.0
        ports:
        - containerPort: 80
