version: "3"
services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  rabbit-mq:
    image: rabbitmq:3-management
    restart: unless-stopped

  jasmin:
    image: jookies/jasmin:0.10
    restart: unless-stopped
    container_name: jasmin
    volumes:
      #- /var/log/jasmin:/var/log/jasmin
      #- /etc/jasmin:/etc/jasmin
      - /var/log/jasmin:/var/log/jasmin
      - /etc/jasmin:/etc/jasmin
    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
      - 15672:15672
      - 5672:5672
    depends_on:
      - redis
      - rabbit-mq
    environment:
      REDIS_CLIENT_HOST: redis
      AMQP_BROKER_HOST: rabbit-mq