//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:39:35 AM BRT 
//


package br.com.poc.model.acpo023.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CliComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CliComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="TipCli" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="IdfcCli" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="99999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CdEstCli" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="C"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TsCnct" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][1-2][0-9][0-9][0-9]-[0-2][0-9][0-5][0-9][0-5][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CnpjGstCnct" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="99999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CliComplexType")
public class CliComplexType {

    @XmlAttribute(name = "TipCli", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tipCli;
    @XmlAttribute(name = "IdfcCli", required = true)
    protected long idfcCli;
    @XmlAttribute(name = "CdEstCli", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cdEstCli;
    @XmlAttribute(name = "TsCnct", required = true)
    protected String tsCnct;
    @XmlAttribute(name = "CnpjGstCnct", required = true)
    protected long cnpjGstCnct;

    /**
     * Gets the value of the tipCli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipCli() {
        return tipCli;
    }

    /**
     * Sets the value of the tipCli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipCli(String value) {
        this.tipCli = value;
    }

    /**
     * Gets the value of the idfcCli property.
     * 
     */
    public long getIdfcCli() {
        return idfcCli;
    }

    /**
     * Sets the value of the idfcCli property.
     * 
     */
    public void setIdfcCli(long value) {
        this.idfcCli = value;
    }

    /**
     * Gets the value of the cdEstCli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdEstCli() {
        return cdEstCli;
    }

    /**
     * Sets the value of the cdEstCli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdEstCli(String value) {
        this.cdEstCli = value;
    }

    /**
     * Gets the value of the tsCnct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTsCnct() {
        return tsCnct;
    }

    /**
     * Sets the value of the tsCnct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTsCnct(String value) {
        this.tsCnct = value;
    }

    /**
     * Gets the value of the cnpjGstCnct property.
     * 
     */
    public long getCnpjGstCnct() {
        return cnpjGstCnct;
    }

    /**
     * Sets the value of the cnpjGstCnct property.
     * 
     */
    public void setCnpjGstCnct(long value) {
        this.cnpjGstCnct = value;
    }

}
