//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:39:35 AM BRT 
//


package br.com.poc.model.acpo023.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnvoRlcCncdComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnvoRlcCncdComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cli" type="{}CliComplexType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CnpjOgm" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="99999999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NmOgm" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="60"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NrRms" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SeqlRms" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DtRms" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-3][0-9][0-1][0-9][1-2][0-9][0-9][0-9]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnvoRlcCncdComplexType", propOrder = {
    "cli"
})
public class EnvoRlcCncdComplexType {

    @XmlElement(name = "Cli", required = true)
    protected List<CliComplexType> cli;
    @XmlAttribute(name = "CnpjOgm", required = true)
    protected long cnpjOgm;
    @XmlAttribute(name = "NmOgm", required = true)
    protected String nmOgm;
    @XmlAttribute(name = "NrRms", required = true)
    protected int nrRms;
    @XmlAttribute(name = "SeqlRms", required = true)
    protected int seqlRms;
    @XmlAttribute(name = "DtRms", required = true)
    protected String dtRms;

    /**
     * Gets the value of the cli property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cli property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCli().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CliComplexType }
     * 
     * 
     */
    public List<CliComplexType> getCli() {
        if (cli == null) {
            cli = new ArrayList<CliComplexType>();
        }
        return this.cli;
    }

    /**
     * Gets the value of the cnpjOgm property.
     * 
     */
    public long getCnpjOgm() {
        return cnpjOgm;
    }

    /**
     * Sets the value of the cnpjOgm property.
     * 
     */
    public void setCnpjOgm(long value) {
        this.cnpjOgm = value;
    }

    /**
     * Gets the value of the nmOgm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmOgm() {
        return nmOgm;
    }

    /**
     * Sets the value of the nmOgm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmOgm(String value) {
        this.nmOgm = value;
    }

    /**
     * Gets the value of the nrRms property.
     * 
     */
    public int getNrRms() {
        return nrRms;
    }

    /**
     * Sets the value of the nrRms property.
     * 
     */
    public void setNrRms(int value) {
        this.nrRms = value;
    }

    /**
     * Gets the value of the seqlRms property.
     * 
     */
    public int getSeqlRms() {
        return seqlRms;
    }

    /**
     * Sets the value of the seqlRms property.
     * 
     */
    public void setSeqlRms(int value) {
        this.seqlRms = value;
    }

    /**
     * Gets the value of the dtRms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtRms() {
        return dtRms;
    }

    /**
     * Sets the value of the dtRms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtRms(String value) {
        this.dtRms = value;
    }

}
