//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 10:39:35 AM BRT 
//


package br.com.poc.model.acpo023.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EnvoRlcCncd_QNAME = new QName("", "EnvoRlcCncd");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnvoRlcCncdComplexType }
     * 
     */
    public EnvoRlcCncdComplexType createEnvoRlcCncdComplexType() {
        return new EnvoRlcCncdComplexType();
    }

    /**
     * Create an instance of {@link CliComplexType }
     * 
     */
    public CliComplexType createCliComplexType() {
        return new CliComplexType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvoRlcCncdComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EnvoRlcCncd")
    public JAXBElement<EnvoRlcCncdComplexType> createEnvoRlcCncd(EnvoRlcCncdComplexType value) {
        return new JAXBElement<EnvoRlcCncdComplexType>(_EnvoRlcCncd_QNAME, EnvoRlcCncdComplexType.class, null, value);
    }

}
